languageCode: en-us
title: John's Site
theme: hugo-flex
enableRobotsTXT: true

params:
  footer: "&copy; 2023 John Sullivan"
  mainSections:
  - portfolio
  - blog
  color: firebrick

menu:
  nav:
  - name: Blog
    url: /blog/
    weight: 1
  - name: Portfolio
    url: /portfolio/
    weight: 2
  - name: Resume
    url: /resume
    weight: 4
  - name: Contact
    url: /contact/
    weight: 5
